services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdfghjkl
      - POSTGRES_DB=taskflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on: 
      - db
    env_file:
      - .env

volumes:
  postgres_data: